### ISSUE TITLE
Bugs found with new update 7/6/2020

### ISSUE THREAD

**Issue by jover-usgs** [dbuscombe-usgs/doodle_labeller#1]
A few bugs/notes

1. In Doodler_optim.py line 207 there is a parentheses missing.

2. When using the -f to load a npy file in the doodler.py script, nothing happens, the dense labelling...this may take a while appears and then quickly ends - see screenshot.
![image](https://user-images.githubusercontent.com/61466548/86611730-173e5680-bf7d-11ea-93d0-bb8b71448fd9.png)

3. When using the -f to load a npy file in the doodler_optim.py script, the CRF computes and then breaks due a 'label_lines' is not defined. See screenshot.

![image](https://user-images.githubusercontent.com/61466548/86611774-2b825380-bf7d-11ea-9020-6f896dfc5ce0.png)

4. Doodle pen/drawing still lags on the water_config whichever the second class is. If you skip the water, the no water doesn't lag. If you do a water, the no water lags.

**Comment by dbuscombe-usgs** [comment]
1 and 3 are now fixed. 2 is because the labels are not in the folder the program expects them to be in (`label_data` - originally, files could be anywhere, but no longer). Need more info on 4 - not sure what you mean

**Comment by dbuscombe-usgs** [comment]
![Screenshot from 2020-07-06 12-39-53](https://user-images.githubusercontent.com/3596509/86633753-e9114480-bf85-11ea-9877-274e32bcbdd9.png)

**Comment by dbuscombe-usgs** [comment]
Hopefully this is fixed on new commit `pre-v0`. On 2), that error occurred because your label images need to be in `data/label_images` (sorry if that not clear). On 4), I have disabled garbage collection and used smaller datatypes so less to draw. Hopeffuly fixed but please report

**Comment by MARDAScience** [comment]
Just pushed a new version. It doesn't fix the slowdown but it may help a little. It uses even less memory now so there is less for the graphics processor to do. Can't (yet) see any other ways to speed things up, but i'll keep researching. please report any differences you observe with the new version - thanks!

**Comment by ddbuscombe** [comment]
Closing this due to lack of activity, but it remains a known bug I am aware of
